SERVER_SETTINGS = {
    "template_directory": "../templates",
    "database_directory": "../database",
    "resources_directory": "../resources",
    "user_photos_directory": "../resources/user_photos",
    "vector_directory": "../vector_store",
    "expert_recommendation_llm_model": "mistral:instruct",
    "expert_recommendation_embeddings": "all-mpnet-base-v2",
    "keywords_llm_model": "camembert/camembert-large",
    "spacy_nlp_fr": "fr_core_news_sm",
    "spacy_nlp_en": "en_core_web_sm",
    "users_csv_file": "../resources/users.csv",
    "users_json_file": "../resources/users.json",
    "linkedin_data_file": "../resources/out.json",
    "access_log_file": "../server_access.log",
    "error_log_file": "../server_error.log",
    "sqlite_db": "users.db",
    "chroma_collection_name": "Experts",
    "zeromq_request_address": "tcp://localhost:5555",
    "zeromq_response_address": "tcp://*:5555",
}
